### ISSUE TITLE
macOS Sierra no longer has /Volumes as world writable

### ISSUE THREAD

**Issue by jason1365** [gniemetz/automount#3]
The script expects write access at the user level to /Volumes/. This is no longer the case for macOS Sierra.

https://derflounder.wordpress.com/2016/09/21/macos-sierras-volumes-folder-is-no-longer-world-writable/

**Comment by gniemetz** [comment]
oh my, this is a tricky one :(

**Comment by gniemetz** [comment]
tried to resolve in dev branch

**Comment by jason1365** [comment]
Could we lose our data if this is set to run?
/etc/periodic/daily/110.clean-tmps

**Comment by gniemetz** [comment]
Good question, maybe it is safer to use the $HOME as the base for the mountpoints?

**Comment by gniemetz** [comment]
In Version 0.90.4 in dev-Branch: The shares are mounted in ${LOGINHOME}/Volumes if on OS version >= 10.12.0 and not root-User, else in /Volumes

**Comment by gniemetz** [comment]
Updated master with v0.90.5

**Comment by unikitty37** [comment]
Is there a fix which will allow it to actually mount the volumes in /Volumes on Sierra? This is the reason I have tried installing it, and it's not particularly clear from the README as to whether this is supported or not…

**Comment by gniemetz** [comment]
It's not possible to mount a network volume in /Volume anymore (at least
from a shell), because the permissions changed since macOS Sierra
Output of "ls -lisaeO@d /Volumes" on macOS High Sierra
721593 0 drwxr-xr-x+ 8 root  wheel  hidden 256 15 Jan 16:16 /Volumes
 0: group:everyone deny
add_file,add_subdirectory,directory_inherit,only_inherit

Another resource
https://derflounder.wordpress.com/2016/09/21/macos-sierras-volumes-folder-is-no-longer-world-writable/

best regards
Gerd

2018-01-15 15:55 GMT+01:00 John Yeates <notifications@github.com>:

**Comment by unikitty37** [comment]
OK, thanks — a shame Apple didn't think of this use case, but not a lot you can do…
